version: "3.8"

services:
    postgres:
        image: postgres:15
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: monitoring_db
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    influxdb:
        image: influxdb:2.7
        container_name: influxdb
        restart: unless-stopped
        ports:
            - "8086:8086"
        volumes:
            - influxdb_data:/var/lib/influxdb2
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: admin
            DOCKER_INFLUXDB_INIT_PASSWORD: supersecret123
            DOCKER_INFLUXDB_INIT_ORG: monitoring_org
            DOCKER_INFLUXDB_INIT_BUCKET: monitoring_bucket
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: secret-token

    mqtt:
        image: eclipse-mosquitto:2
        container_name: mosquitto
        restart: unless-stopped
        ports:
            - "1883:1883" # MQTT default
            - "9001:9001" # WebSocket (optional)
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log

volumes:
    postgres_data:
    redis_data:
    influxdb_data:
